from typing import List
from enum import Enum

from character import Character


class RelicsManager:
    class RelicRarity(Enum):
        NONE = 0
        STARTER = 1
        COMMON = 2
        UNCOMMON = 3
        RARE = 4
        SHOP = 5
        EVENT = 6
        ANCIENT = 7

    CHARCATER_RELICS = {
        Character.IRONCLAD: [
            "Brimstone",
            "BurningBlood",
            "CharonsAshes",
            "DemonTongue",
            "PaperPhrog",
            "RedSkull",
            "RuinedHelmet",
            "SelfFormingClay"
        ],
        Character.SILENT: [
            "HelicalDart",
            "NinjaScroll",
            "PaperKrane",
            "RingOfTheSnake",
            "SneckoSkull",
            "Tingsha",
            "ToughBandages",
            "TwistedFunnel"
        ],
        Character.REGENT: [
            "DivineRight",
            "FencingManual",
            "GalacticDust",
            "LunarPastry",
            "MiniRegent",
            "OrangeDough",
            "Regalite",
            "VitruvianMinion"
        ],
        Character.NECROBINDER: [
            "BigHat",
            "BoneFlute",
            "BookRepairKnife",
            "Bookmark",
            "BoundPhylactery",
            "FuneraryMask",
            "IvoryTile",
            "UndyingSigil"
        ],
        Character.DEFECT: [
            "CrackedCore",
            "DataDisk",
            "EmotionChip",
            "GoldPlatedCables",
            "PowerCell",
            "Metronome",
            "RunicCapacitor",
            "SymbioticVirus"
        ]
    }

    RELIC_RARITY_MAPPING = {
        "Akabeko": RelicRarity.UNCOMMON,
        "AlchemicalCoffer": RelicRarity.ANCIENT,
        "AmethystAubergine": RelicRarity.COMMON,
        "Anchor": RelicRarity.COMMON,
        "ArcaneScroll": RelicRarity.ANCIENT,
        "ArchaicTooth": RelicRarity.ANCIENT,
        "ArtOfWar": RelicRarity.RARE,
        "Astrolabe": RelicRarity.ANCIENT,
        "BagOfMarbles": RelicRarity.UNCOMMON,
        "BagOfPreparation": RelicRarity.COMMON,
        "BeatingRemnant": RelicRarity.RARE,
        "BeautifulBracelet": RelicRarity.ANCIENT,
        "Bellows": RelicRarity.UNCOMMON,
        "BeltBuckle": RelicRarity.SHOP,
        "BigHat": RelicRarity.RARE,
        "BigMushroom": RelicRarity.EVENT,
        "BiiigHug": RelicRarity.ANCIENT,
        "BingBong": RelicRarity.EVENT,
        "BlackBlood": RelicRarity.STARTER,
        "BlackStar": RelicRarity.ANCIENT,
        "BlessedAntler": RelicRarity.ANCIENT,
        "BloodSoakedRose": RelicRarity.ANCIENT,
        "BloodVial": RelicRarity.COMMON,
        "BoneFlute": RelicRarity.COMMON,
        "BoneTea": RelicRarity.EVENT,
        "Bookmark": RelicRarity.RARE,
        "BookOfFiveRings": RelicRarity.COMMON,
        "BookRepairKnife": RelicRarity.UNCOMMON,
        "BoomingConch": RelicRarity.ANCIENT,
        "BoundPhylactery": RelicRarity.STARTER,
        "BowlerHat": RelicRarity.UNCOMMON,
        "Bread": RelicRarity.SHOP,
        "BrilliantScarf": RelicRarity.ANCIENT,
        "Brimstone": RelicRarity.SHOP,
        "BronzeScales": RelicRarity.COMMON,
        "BurningBlood": RelicRarity.STARTER,
        "BurningSticks": RelicRarity.SHOP,
        "Byrdpip": RelicRarity.EVENT,
        "CallingBell": RelicRarity.ANCIENT,
        "Candelabra": RelicRarity.UNCOMMON,
        "CaptainsWheel": RelicRarity.RARE,
        "Cauldron": RelicRarity.SHOP,
        "CentennialPuzzle": RelicRarity.COMMON,
        "Chandelier": RelicRarity.RARE,
        "CharonsAshes": RelicRarity.RARE,
        "ChemicalX": RelicRarity.SHOP,
        "ChoicesParadox": RelicRarity.ANCIENT,
        "ChosenCheese": RelicRarity.EVENT,
        "Circlet": RelicRarity.NONE,
        "Claws": RelicRarity.ANCIENT,
        "CloakClasp": RelicRarity.RARE,
        "CrackedCore": RelicRarity.STARTER,
        "Crossbow": RelicRarity.ANCIENT,
        "CursedPearl": RelicRarity.ANCIENT,
        "DarkstonePeriapt": RelicRarity.EVENT,
        "DataDisk": RelicRarity.COMMON,
        "DaughterOfTheWind": RelicRarity.EVENT,
        "DelicateFrond": RelicRarity.ANCIENT,
        "DemonTongue": RelicRarity.RARE,
        "DeprecatedRelic": RelicRarity.NONE,
        "DiamondDiadem": RelicRarity.ANCIENT,
        "DingyRug": RelicRarity.SHOP,
        "DistinguishedCape": RelicRarity.ANCIENT,
        "DivineDestiny": RelicRarity.STARTER,
        "DivineRight": RelicRarity.STARTER,
        "DollysMirror": RelicRarity.SHOP,
        "DragonFruit": RelicRarity.SHOP,
        "DreamCatcher": RelicRarity.EVENT,
        "Driftwood": RelicRarity.ANCIENT,
        "DustyTome": RelicRarity.ANCIENT,
        "Ectoplasm": RelicRarity.ANCIENT,
        "ElectricShrymp": RelicRarity.ANCIENT,
        "EmberTea": RelicRarity.EVENT,
        "EmotionChip": RelicRarity.RARE,
        "EmptyCage": RelicRarity.ANCIENT,
        "EternalFeather": RelicRarity.UNCOMMON,
        "FakeAnchor": RelicRarity.EVENT,
        "FakeBloodVial": RelicRarity.EVENT,
        "FakeHappyFlower": RelicRarity.EVENT,
        "FakeLeesWaffle": RelicRarity.EVENT,
        "FakeMango": RelicRarity.EVENT,
        "FakeMerchantsRug": RelicRarity.EVENT,
        "FakeOrichalcum": RelicRarity.EVENT,
        "FakeSneckoEye": RelicRarity.EVENT,
        "FakeStrikeDummy": RelicRarity.EVENT,
        "FakeVenerableTeaSet": RelicRarity.EVENT,
        "FencingManual": RelicRarity.COMMON,
        "FestivePopper": RelicRarity.COMMON,
        "Fiddle": RelicRarity.ANCIENT,
        "ForgottenSoul": RelicRarity.EVENT,
        "FragrantMushroom": RelicRarity.EVENT,
        "FresnelLens": RelicRarity.EVENT,
        "FrozenEgg": RelicRarity.RARE,
        "FuneraryMask": RelicRarity.UNCOMMON,
        "FurCoat": RelicRarity.ANCIENT,
        "GalacticDust": RelicRarity.UNCOMMON,
        "GamblingChip": RelicRarity.RARE,
        "GamePiece": RelicRarity.RARE,
        "GhostSeed": RelicRarity.SHOP,
        "Girya": RelicRarity.RARE,
        "GlassEye": RelicRarity.ANCIENT,
        "Glitter": RelicRarity.ANCIENT,
        "GnarledHammer": RelicRarity.SHOP,
        "GoldenCompass": RelicRarity.ANCIENT,
        "GoldenPearl": RelicRarity.ANCIENT,
        "GoldPlatedCables": RelicRarity.UNCOMMON,
        "Gorget": RelicRarity.COMMON,
        "GremlinHorn": RelicRarity.UNCOMMON,
        "HandDrill": RelicRarity.EVENT,
        "HappyFlower": RelicRarity.COMMON,
        "HelicalDart": RelicRarity.RARE,
        "HistoryCourse": RelicRarity.EVENT,
        "HornCleat": RelicRarity.UNCOMMON,
        "IceCream": RelicRarity.RARE,
        "InfusedCore": RelicRarity.STARTER,
        "IntimidatingHelmet": RelicRarity.RARE,
        "IronClub": RelicRarity.ANCIENT,
        "IvoryTile": RelicRarity.RARE,
        "JeweledMask": RelicRarity.ANCIENT,
        "JewelryBox": RelicRarity.ANCIENT,
        "JossPaper": RelicRarity.UNCOMMON,
        "JuzuBracelet": RelicRarity.COMMON,
        "Kifuda": RelicRarity.SHOP,
        "Kunai": RelicRarity.RARE,
        "Kusarigama": RelicRarity.UNCOMMON,
        "Lantern": RelicRarity.COMMON,
        "LargeCapsule": RelicRarity.ANCIENT,
        "LastingCandy": RelicRarity.RARE,
        "LavaLamp": RelicRarity.SHOP,
        "LavaRock": RelicRarity.ANCIENT,
        "LeadPaperweight": RelicRarity.ANCIENT,
        "LeafyPoultice": RelicRarity.ANCIENT,
        "LeesWaffle": RelicRarity.SHOP,
        "LetterOpener": RelicRarity.UNCOMMON,
        "LizardTail": RelicRarity.RARE,
        "LoomingFruit": RelicRarity.ANCIENT,
        "LordsParasol": RelicRarity.ANCIENT,
        "LostCoffer": RelicRarity.ANCIENT,
        "LostWisp": RelicRarity.EVENT,
        "LuckyFysh": RelicRarity.UNCOMMON,
        "LunarPastry": RelicRarity.RARE,
        "Mango": RelicRarity.RARE,
        "MassiveScroll": RelicRarity.ANCIENT,
        "MawBank": RelicRarity.EVENT,
        "MealTicket": RelicRarity.COMMON,
        "MeatCleaver": RelicRarity.ANCIENT,
        "MeatOnTheBone": RelicRarity.RARE,
        "MembershipCard": RelicRarity.SHOP,
        "MercuryHourglass": RelicRarity.UNCOMMON,
        "Metronome": RelicRarity.RARE,
        "MiniatureCannon": RelicRarity.UNCOMMON,
        "MiniatureTent": RelicRarity.SHOP,
        "MiniRegent": RelicRarity.RARE,
        "MoltenEgg": RelicRarity.RARE,
        "MrStruggles": RelicRarity.EVENT,
        "MummifiedHand": RelicRarity.RARE,
        "MusicBox": RelicRarity.ANCIENT,
        "MysticLighter": RelicRarity.SHOP,
        "NeowsTorment": RelicRarity.ANCIENT,
        "NewLeaf": RelicRarity.ANCIENT,
        "NinjaScroll": RelicRarity.SHOP,
        "Nunchaku": RelicRarity.UNCOMMON,
        "NutritiousOyster": RelicRarity.ANCIENT,
        "NutritiousSoup": RelicRarity.ANCIENT,
        "OddlySmoothStone": RelicRarity.COMMON,
        "OldCoin": RelicRarity.RARE,
        "OrangeDough": RelicRarity.RARE,
        "Orichalcum": RelicRarity.UNCOMMON,
        "OrnamentalFan": RelicRarity.UNCOMMON,
        "Orrery": RelicRarity.SHOP,
        "PaelsBlood": RelicRarity.ANCIENT,
        "PaelsClaw": RelicRarity.ANCIENT,
        "PaelsEye": RelicRarity.ANCIENT,
        "PaelsFlesh": RelicRarity.ANCIENT,
        "PaelsGrowth": RelicRarity.ANCIENT,
        "PaelsHorn": RelicRarity.ANCIENT,
        "PaelsLegion": RelicRarity.ANCIENT,
        "PaelsTears": RelicRarity.ANCIENT,
        "PaelsTooth": RelicRarity.ANCIENT,
        "PaelsWing": RelicRarity.ANCIENT,
        "PandorasBox": RelicRarity.ANCIENT,
        "Pantograph": RelicRarity.UNCOMMON,
        "PaperKrane": RelicRarity.RARE,
        "PaperPhrog": RelicRarity.UNCOMMON,
        "ParryingShield": RelicRarity.UNCOMMON,
        "Pear": RelicRarity.UNCOMMON,
        "Pendulum": RelicRarity.COMMON,
        "PenNib": RelicRarity.UNCOMMON,
        "Permafrost": RelicRarity.COMMON,
        "PetrifiedToad": RelicRarity.UNCOMMON,
        "PhilosophersStone": RelicRarity.ANCIENT,
        "PhylacteryUnbound": RelicRarity.STARTER,
        "Planisphere": RelicRarity.UNCOMMON,
        "Pocketwatch": RelicRarity.RARE,
        "PollinousCore": RelicRarity.EVENT,
        "Pomander": RelicRarity.ANCIENT,
        "PotionBelt": RelicRarity.COMMON,
        "PowerCell": RelicRarity.RARE,
        "PrayerWheel": RelicRarity.RARE,
        "PrecariousShears": RelicRarity.ANCIENT,
        "PreciseScissors": RelicRarity.ANCIENT,
        "PreservedFog": RelicRarity.ANCIENT,
        "PrismaticGem": RelicRarity.ANCIENT,
        "PumpkinCandle": RelicRarity.ANCIENT,
        "PunchDagger": RelicRarity.SHOP,
        "RadiantPearl": RelicRarity.ANCIENT,
        "RainbowRing": RelicRarity.RARE,
        "RazorTooth": RelicRarity.RARE,
        "RedMask": RelicRarity.UNCOMMON,
        "RedSkull": RelicRarity.COMMON,
        "Regalite": RelicRarity.UNCOMMON,
        "RegalPillow": RelicRarity.COMMON,
        "ReptileTrinket": RelicRarity.UNCOMMON,
        "RingingTriangle": RelicRarity.SHOP,
        "RingOfTheDrake": RelicRarity.STARTER,
        "RingOfTheSnake": RelicRarity.STARTER,
        "RippleBasin": RelicRarity.UNCOMMON,
        "RoyalPoison": RelicRarity.EVENT,
        "RoyalStamp": RelicRarity.SHOP,
        "RuinedHelmet": RelicRarity.RARE,
        "RunicCapacitor": RelicRarity.SHOP,
        "RunicPyramid": RelicRarity.ANCIENT,
        "Sai": RelicRarity.ANCIENT,
        "SandCastle": RelicRarity.ANCIENT,
        "ScreamingFlagon": RelicRarity.SHOP,
        "ScrollBoxes": RelicRarity.ANCIENT,
        "SeaGlass": RelicRarity.ANCIENT,
        "SealOfGold": RelicRarity.ANCIENT,
        "SelfFormingClay": RelicRarity.UNCOMMON,
        "SereTalon": RelicRarity.ANCIENT,
        "Shovel": RelicRarity.RARE,
        "Shuriken": RelicRarity.RARE,
        "SignetRing": RelicRarity.ANCIENT,
        "SilverCrucible": RelicRarity.ANCIENT,
        "SlingOfCourage": RelicRarity.SHOP,
        "SmallCapsule": RelicRarity.ANCIENT,
        "SneckoEye": RelicRarity.ANCIENT,
        "SneckoSkull": RelicRarity.COMMON,
        "Sozu": RelicRarity.ANCIENT,
        "SparklingRouge": RelicRarity.UNCOMMON,
        "SpikedGauntlets": RelicRarity.ANCIENT,
        "StoneCalendar": RelicRarity.RARE,
        "StoneCracker": RelicRarity.UNCOMMON,
        "StoneHumidifier": RelicRarity.ANCIENT,
        "Storybook": RelicRarity.ANCIENT,
        "Strawberry": RelicRarity.COMMON,
        "StrikeDummy": RelicRarity.COMMON,
        "SturdyClamp": RelicRarity.RARE,
        "SwordOfJade": RelicRarity.EVENT,
        "SwordOfStone": RelicRarity.EVENT,
        "SymbioticVirus": RelicRarity.UNCOMMON,
        "TanxsWhistle": RelicRarity.ANCIENT,
        "TeaOfDiscourtesy": RelicRarity.EVENT,
        "TheAbacus": RelicRarity.SHOP,
        "TheBoot": RelicRarity.EVENT,
        "TheCourier": RelicRarity.RARE,
        "ThrowingAxe": RelicRarity.ANCIENT,
        "Tingsha": RelicRarity.UNCOMMON,
        "TinyMailbox": RelicRarity.COMMON,
        "ToastyMittens": RelicRarity.ANCIENT,
        "Toolbox": RelicRarity.SHOP,
        "TouchOfOrobas": RelicRarity.ANCIENT,
        "ToughBandages": RelicRarity.RARE,
        "ToxicEgg": RelicRarity.RARE,
        "ToyBox": RelicRarity.ANCIENT,
        "TriBoomerang": RelicRarity.ANCIENT,
        "TungstenRod": RelicRarity.RARE,
        "TuningFork": RelicRarity.UNCOMMON,
        "TwistedFunnel": RelicRarity.UNCOMMON,
        "UnceasingTop": RelicRarity.RARE,
        "UndyingSigil": RelicRarity.SHOP,
        "UnsettlingLamp": RelicRarity.RARE,
        "Vajra": RelicRarity.COMMON,
        "Vambrace": RelicRarity.UNCOMMON,
        "VelvetChoker": RelicRarity.ANCIENT,
        "VenerableTeaSet": RelicRarity.COMMON,
        "VeryHotCocoa": RelicRarity.ANCIENT,
        "VexingPuzzlebox": RelicRarity.RARE,
        "VitruvianMinion": RelicRarity.SHOP,
        "WarHammer": RelicRarity.ANCIENT,
        "WarPaint": RelicRarity.COMMON,
        "Whetstone": RelicRarity.COMMON,
        "WhisperingEarring": RelicRarity.ANCIENT,
        "WhiteBeastStatue": RelicRarity.RARE,
        "WhiteStar": RelicRarity.RARE,
        "WingCharm": RelicRarity.SHOP,
        "WongoCustomerAppreciationBadge": RelicRarity.EVENT,
        "WongosMysteryTicket": RelicRarity.EVENT,
        "YummyCookie": RelicRarity.ANCIENT
    }

    @staticmethod
    def get_relic_rarity(relic_name: str) -> RelicRarity:
        return RelicsManager.RELIC_RARITY_MAPPING[relic_name]

    @staticmethod
    def get_character_relics(character: Character) -> List[str]:
        return RelicsManager.CHARCATER_RELICS[character]

    @staticmethod
    def get_shared_relics() -> List[str]:
        return [
            "Akabeko",
			"AmethystAubergine",
			"Anchor",
			"ArtOfWar",
			"BagOfMarbles",
			"BagOfPreparation",
			"BeatingRemnant",
			"Bellows",
			"BeltBuckle",
			"BloodVial",
			"BookOfFiveRings",
			"BowlerHat",
			"Bread",
			"BronzeScales",
			"BurningSticks",
			"Candelabra",
			"CaptainsWheel",
			"Cauldron",
			"CentennialPuzzle",
			"Chandelier",
			"ChemicalX",
			"CloakClasp",
			"DingyRug",
			"DollysMirror",
			"DragonFruit",
			"EternalFeather",
			"FestivePopper",
			"FresnelLens",
			"FrozenEgg",
			"GamblingChip",
			"GamePiece",
			"GhostSeed",
			"Girya",
			"GnarledHammer",
			"Gorget",
			"GremlinHorn",
			"HappyFlower",
			"HornCleat",
			"IceCream",
			"IntimidatingHelmet",
			"JossPaper",
			"JuzuBracelet",
			"Kifuda",
			"Kunai",
			"Kusarigama",
			"Lantern",
			"LastingCandy",
			"LavaLamp",
			"LeesWaffle",
			"LetterOpener",
			"LizardTail",
			"LoomingFruit",
			"LuckyFysh",
			"Mango",
			"MealTicket",
			"MeatOnTheBone",
			"MembershipCard",
			"MercuryHourglass",
			"MiniatureCannon",
			"MiniatureTent",
			"MoltenEgg",
			"MummifiedHand",
			"MysticLighter",
			"Nunchaku",
			"OddlySmoothStone",
			"OldCoin",
			"Orichalcum",
			"OrnamentalFan",
			"Orrery",
			"Pantograph",
			"ParryingShield",
			"Pear",
			"PenNib",
			"Pendulum",
			"Permafrost",
			"PetrifiedToad",
			"Planisphere",
			"Pocketwatch",
			"PotionBelt",
			"PrayerWheel",
			"PunchDagger",
			"RainbowRing",
			"RazorTooth",
			"RedMask",
			"RegalPillow",
			"ReptileTrinket",
			"RingingTriangle",
			"RippleBasin",
			"RoyalStamp",
			"ScreamingFlagon",
			"Shovel",
			"Shuriken",
			"SlingOfCourage",
			"SparklingRouge",
			"StoneCalendar",
			"StoneCracker",
			"Strawberry",
			"StrikeDummy",
			"SturdyClamp",
			"TheAbacus",
			"TheCourier",
			"TinyMailbox",
			"Toolbox",
			"ToxicEgg",
			"TungstenRod",
			"TuningFork",
			"UnceasingTop",
			"UnsettlingLamp",
			"Vajra",
			"Vambrace",
			"VenerableTeaSet",
			"VeryHotCocoa",
			"VexingPuzzlebox",
			"WarPaint",
			"Whetstone",
			"WhiteBeastStatue",
			"WhiteStar",
			"WingCharm"
        ]
